config/routes.rb
Rails.application.routes.draw do

  root 'recipes#index'

  resources :recipes do
    resources :steps
    resources :ingredients
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/datum.rb
class Datum < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  validates :name, presence: true
  validates :quantity, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :steps, dependent: :destroy
  has_many :ingredients
  validates :title, presence: true
  validates :description, presence: true
  validates :cook_time, presence: true, numericality: true
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
  validates :order, presence: true
  validates :directions, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def create
    @recipe = Recipe.find_by id: params[:recipe_id]
    @ingredient = Ingredient.new
    @ingredient.name = params[:ingredient][:name]
    @ingredient.quantity = params[:ingredient][:quantity]
    @ingredient.unit = params[:ingredient][:unit]
    @ingredient.recipe_id = params[:recipe_id]
    @ingredient.save
    redirect_to edit_recipe_path(@recipe)
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])
    @ingredient.name = params[:ingredient][:name]
    @ingredient.quantity = params[:ingredient][:quantity]
    @ingredient.unit = params[:ingredient][:unit]
    @ingredient.save
    redirect_to edit_recipe_path(@recipe)
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])
    @ingredient.destroy
    redirect_to edit_recipe_path(@recipe)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find_by id: params[:id]
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new
    @recipe.title = params[:recipe][:title]
    @recipe.description = params[:recipe][:description]
    @recipe.cook_time = params[:recipe][:cook_time]
    if @recipe.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @step = Step.new
    @ingredient = Ingredient.new
  end

  def update
    @recipe = Recipe.find_by id: params[:id]
    @recipe.title = params[:recipe][:title]
    @recipe.description = params[:recipe][:description]
    @recipe.cook_time = params[:recipe][:cook_time]
    if @recipe.save
      redirect_to recipe_path
    else
      @step = Step.new
      @ingredient = Ingredient.new
      render :edit
    end
  end

  def destroy
    Recipe.destroy params[:id]
    redirect_to root_path
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.new
    @step.order = params[:step][:order]
    @step.directions = params[:step][:directions]
    @step.save
    redirect_to edit_recipe_path(@recipe)
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.find(params[:id])
    @step.destroy
    redirect_to edit_recipe_path(@recipe)
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.find(params[:id])
    @step.order = params[:step][:order]
    @step.directions = params[:step][:directions]
    @step.save
    redirect_to edit_recipe_path(@recipe)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/_form.html.erb
<%= form_for ([@recipe, @ingredient]), html: {class: "form-horizontal"} do |f| %>

<div class="form-group">
  <%= f.label :name, class: "control-label" %>
  <%= f.text_field :name, class: "form-control", required: true%>
</div>

<div class="form-group">
  <%= f.label :quantity, class: "control-label" %>
  <%= f.text_field :quantity, class: "form-control", required: true %>
</div>

<div class="form-group">
  <%= f.label :unit, class: "control-label" %>
  <%= f.text_field :unit, class: "form-control" %>
</div>


  <%= f.submit class: "btn btn-primary", value: "Add ingredient"%>



<% end %>

app/views/ingredients/edit.html.erb
<%= render partial: 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <h1><%= link_to "Recipe Box", root_path %></h1>
        <h3>A place to store all of your favorite recipes</h3>
        <nav>
          <%= link_to "Add Recipe", new_recipe_path %>
        </nav>
      </header>
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

    <ul>
    <% @recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @recipe, html: {class: "form-inline"}  do |f| %>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control", required: true %>
</div>

<div class="form-group">
  <%= f.label :cook_time %>
  <%= f.text_field :cook_time, required: true %>
</div>

<div class="form-group">
  <%= f.submit class: "btn btn-primary"%>
</div>

<% end %>

app/views/recipes/edit.html.erb
<%= render partial: 'form' %>

<div class="edit-ingredients">
  <ul class="ingredients">
  <% @recipe.ingredients.each do |ingredient| %>
    <li><%= ingredient.quantity %>
      <% if ingredient.unit == nil %>
      <%= ingredient.name.pluralize(ingredient.quantity.to_i) %>
      <% else %>
      <%= ingredient.unit %> <%= ingredient.name %>
      <% end %>
      <%= link_to "Edit", edit_recipe_ingredient_path(ingredient.recipe, ingredient) %>
      <%= link_to "Delete", [ingredient.recipe, ingredient], method: :delete, data: { confirm: "Are you sure you want to delete this ingredient?"} %>
      </li>
  <% end %>
  </ul>
  <%= render partial: 'ingredients/form' %>
</div>



<ol class="steps">
  <% @recipe.steps.order(:order).each do |step| %>
  <li><%= step.directions %>
    <%= link_to "Edit", edit_recipe_step_path(step.recipe, step) %>
    <%= link_to "Delete", [step.recipe, step], method: :delete, data: { confirm: "Are you sure you want to delete this step?"} %>
  </li>
  <% end %>
</ol>
<p>Add Step:</p>
<%= render partial: 'steps/form' %>

app/views/recipes/index.html.erb
<% @recipes.each do |recipe| %>
<div class="recipe-display">
  <h3><%= link_to recipe.title, recipe_path(recipe) %></h3>
  <h4><%= recipe.cook_time %> min</h4>
  <h5><%= recipe.description %></h5>
</div>

<% end %>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/show.html.erb
<div class="recipe page-header">
  <div class="recipe-description">
    <h3><%= @recipe.title %></h3>
    <h4><%= @recipe.cook_time %> minutes</h4>
    <p class="lead"><%= @recipe.description %></p>
    <%= link_to "Edit", edit_recipe_path(@recipe) %>
    <%= link_to "Delete", recipe_path(@recipe), method: :delete, data: {confirm: 'Are you sure you want to delete this recipe?'} %>
  </div>
  <ul class="ingredients">
  <% @recipe.ingredients.each do |ingredient| %>
    <li><%= ingredient.quantity %>
      <% if ingredient.unit == nil %>
      <%= ingredient.name.pluralize(ingredient.quantity.to_i) %>
      <% else %>
      <%= ingredient.unit %> <%= ingredient.name %></li>
      <% end %>
  <% end %>
  </ul>
</div>



<ol class="steps">
  <% @recipe.steps.order(:order).each do |step| %>
  <li><%= step.directions %></li>

  <% end %>
</ol>

app/views/steps/_form.html.erb
<%= form_for ([@recipe, @step]), html: {class: "form-inline"} do |f| %>
<div class="form-group">
  <%= f.label :order %>
  <%= f.number_field :order, required: true%>
</div>

<div class="form-group">
  <%= f.label :directions %>
  <%= f.text_area :directions, class: "form-control", required: true %>
</div>

<%= f.submit class: "btn btn-primary"%>

<% end %>

app/views/steps/edit.html.erb
<%= render 'form'%>

app/views/steps/new.html.erb
<%= render 'form' %>